### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by AsimKhan2019** [dodoburner/tip-calculator#1]
Peer to Peer Code Review of Dorian's tipping calculator.

**Comment by AsimKhan2019** [comment]
Nicely done, code can be improved using the DRY approach.  People can be 1 or 2, but not 0.1.  Using classes to assign styles to elements is better. Negative numbers are handled properly, except for -3 customers.

**Comment by AsimKhan2019** [comment]
The tip calculator only works after focusing away from the bill amount.

**Comment by dodoburner** [comment]
Thank you for your input, I have resolved the issues.
